import { drawSectionTitle } from "../pdfDrawHelpers.js";
import { PDF_THEME } from "../theme.js";

const { colors, fonts, fontSizes } = PDF_THEME;

export const renderAISummarySection = (
  doc,
  { headline, narrative, insights, recommendations, aiAvailable },
) => {
  drawSectionTitle(doc, "AI Summary & Recommendations", {
    subtitle: aiAvailable
      ? "Generated by ExpenseTracker AI Insights"
      : "AI analysis unavailable for this report",
  });

  if (headline) {
    doc
      .fillColor(colors.text)
      .font(fonts.bold)
      .fontSize(fontSizes.h2)
      .text(headline);
    doc.moveDown(0.3);
  }

  if (narrative) {
    doc
      .fillColor(colors.textMuted)
      .font(fonts.regular)
      .fontSize(fontSizes.body)
      .text(narrative);
    doc.moveDown(0.8);
  }

  if (insights?.length) {
    doc
      .fillColor(colors.text)
      .font(fonts.bold)
      .fontSize(fontSizes.h2)
      .text("Key Insights");
    doc.moveDown(0.3);
    insights.forEach((i) => {
      doc
        .fillColor(colors.accent)
        .font(fonts.bold)
        .fontSize(fontSizes.small)
        .text(`• ${i.title}`);
      doc
        .fillColor(colors.textMuted)
        .font(fonts.regular)
        .fontSize(fontSizes.small)
        .text(i.body, { indent: 12 });
      doc.moveDown(0.3);
    });
  }

  if (recommendations?.length) {
    doc.moveDown(0.3);
    doc
      .fillColor(colors.text)
      .font(fonts.bold)
      .fontSize(fontSizes.h2)
      .text("Recommendations");
    doc.moveDown(0.3);
    recommendations.forEach((r, idx) => {
      doc
        .fillColor(colors.text)
        .font(fonts.bold)
        .fontSize(fontSizes.small)
        .text(`${idx + 1}. ${r.title}`);
      doc
        .fillColor(colors.textMuted)
        .font(fonts.regular)
        .fontSize(fontSizes.small)
        .text(r.description, { indent: 12 });
      doc.moveDown(0.3);
    });
  }

  if (!aiAvailable) {
    doc
      .fillColor(colors.textSubtle)
      .font(fonts.oblique)
      .fontSize(fontSizes.small)
      .text(
        "Configure an AI provider (ANTHROPIC_API_KEY or OPENAI_API_KEY) to enable narrative summaries in future monthly reports.",
      );
  }
};
